//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clutch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string dni { get; set; }
        public bool vacaciones { get; set; }
        public int diasVacaciones { get; set; }
        public System.DateTime alta { get; set; }
        public Nullable<System.DateTime> baja { get; set; }
        public string contraseña { get; set; }
    }
}
