//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clutch
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidencia
    {
        public int id { get; set; }
        public int idEmpleado { get; set; }
        public string incidencia1 { get; set; }
        public string tipo { get; set; }
        public System.DateTime fecha { get; set; }
        public bool resuelta { get; set; }
    }
}
