//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clutch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jornada
    {
        public int id { get; set; }
        public System.DateTime Entrada { get; set; }
        public Nullable<System.DateTime> Salida { get; set; }
        public int idEmpleado { get; set; }
        public Nullable<int> pedidos { get; set; }
        public double sueldo { get; set; }
        public double horas { get; set; }
        public double sueldoHoy { get; set; }
    }
}
